#!/bin/bash

#this script 
#updates everything needeeded to 
#to use Debian 11 on any matchine 


sudo apt update
sudo apt upgrade

# Install tool for hardware detection
#sudo apt install nvidia-detect

# Perform the scan
#sudo nvidia-detect

# Install recommended driver. It is nvidia-driver for me. Yours could be different.
#sudo apt install nvidia-driver

#amd drivers
#sudo apt install firmware-linux firmware-linux-nonfree libdrm-amdgpu1 xserver-xorg-video-amdgpu


sudo apt install aptitude

sudo apt install firmware-linux firmware-linux-nonfree libdrm-amdgpu1 xserver-xorg-video-amdgpu


sudo apt install mesa-vulkan-drivers libvulkan1 vulkan-tools vulkan-validationlayers



sudo apt install build-essential dkms linux-headers-$(uname -r)


sudo apt install ttf-mscorefonts-installer rar unrar libavcodec-extra gstreamer1.0-libav gstreamer1.0-plugins-ugly gstreamer1.0-vaapi

sudo apt install fonts-crosextra-carlito fonts-crosextra-caladea



sudo apt install ufw
sudo ufw enable

sudo apt install tlp


sudo apt install synaptic

sudo apt install build-essential dkms linux-headers-$(uname -r)



sudo apt install mesa-vulkan-drivers libvulkan1 vulkan-tools vulkan-utils vulkan-validationlayers


sudo apt install mesa-opencl-icd



sudo apt install ttf-mscorefonts-installer rar unrar libavcodec-extra gstreamer1.0-libav gstreamer1.0-plugins-ugly gstreamer1.0-vaapi



sudo apt install vlc

sudo apt install chrome-gnome-shell


sudo apt install firmware-iwlwifi firmware-atheros firmware-realtek firmware-linux-nonfree
