#!/bin/bash

#this script has been created by Melquiceded B.V
#and it updates everything needeeded
#on Debian 11

sudo apt update
sudo apt upgrade

# Install tool for hardware detection
#sudo apt install nvidia-detect

# Perform the scan
#sudo nvidia-detect

# Install recommended driver. It is nvidia-driver for me. Yours could be different.
#sudo apt install nvidia-driver

#amd drivers
#sudo apt install firmware-linux firmware-linux-nonfree libdrm-amdgpu1 xserver-xorg-video-amdgpu


#install aptitude
sudo apt install aptitude
#install none free for amd GPU
sudo apt install firmware-linux firmware-linux-nonfree libdrm-amdgpu1 xserver-xorg-video-amdgpu -y
#Vulkan Drivers
sudo apt install mesa-vulkan-drivers libvulkan1 vulkan-tools vulkan-validationlayers -y
#linux headers
sudo apt install build-essential dkms linux-headers-$(uname -r) -y 
#fonts from microsoft
sudo apt install ttf-mscorefonts-installer rar unrar libavcodec-extra gstreamer1.0-libav gstreamer1.0-plugins-ugly gstreamer1.0-vaapi -y 
#more fonts
sudo apt install fonts-crosextra-carlito fonts-crosextra-caladea -y 
#install firewall
sudo apt install ufw -y 
sudo ufw enable #activate the firewall 
#power manager for laptop 
sudo apt install tlp -y 
#package manager synapti 
sudo apt install synapti -y
#Mesa drivers for GPU
sudo apt install mesa-opencl-icd -y
#install vlc media player
sudo apt install vlc -y
#install gnome shell 
sudo apt install chrome-gnome-shell -y
#install wifi drivers 
sudo apt install firmware-iwlwifi firmware-atheros firmware-realtek firmware-linux-nonfree -y
#display a nice logo of the distro
sudo apt install neofetch -y 
#helps to view files in the terminal
sudo apt install ranger -y
#install a voice reader for the terminal 
sudo apt install espeak-ng/stable -y
#helps when you delete files to be able to restore them 
sudo apt install trash-cli/stable -y
#ftp client 
sudo apt install lftp -y 
#man variant to
sudo apt install tldr -y 


#games 

#pacman
sudo apt install pacman4console -y 
#snake
sudo apt install nsnake -y 
#space 
sudo apt install ninvaders -y 
#tetrix
sudo apt install bastet -y 


#Media
echo "installing variaty"
sleep 1
sudo apt install variety


echo "Installing Wine"
sleep 1
sudo dpkg --add-architecture i386
sudo mkdir -pm755 /etc/apt/keyrings
sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/debian/dists/bullseye/winehq-bullseye.sources
sudo apt update
sudo apt install --install-recommends winehq-stable

echo "installing ink"
sleep 1
sudo apt install inkscape

echo "installing obs-studio"
sleep 1
sudo apt install obs-studio

echo "Htop install"
sleep 1
sudo apt install htop

echo "Notification Lib"; 
sleep 1 
sudo apt install libnotify-bin














