#!/bin/bash

echo "Setting Merge as default Git Action"
git config pull.rebase false  # merge (the default strategy)
git pull
git add -A
git commit -a
git push

Say "The Git Push , Has Been Completed , Sucessfully"











