#!/bin/bash


echo "sudo fallocate -l 4G /swapfile"
echo "sudo chmod 600 /swapfile"
echo "sudo mkswap /swapfile"
echo "sudo swapon /swapfile"
echo "sudo swapon --show"
echo "echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab"
