#!/bin/bash
sudo apt install apt-transport-https dirmngr
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb https://download.mono-project.com/repo/debian vs-buster main" | sudo tee /etc/apt/sources.list.d/mono-official-vs.list
sudo apt update

sudo apt-get install monodevelop

echo "Gnome Terminal addaptation"

    cd /usr/lib
    sudo mkdir gnome-terminal
    cd gnome-terminal
    sudo ln -s /usr/libexec/gnome-terminal-server

