#!/bin/bash

ftp_site=$1
username=$2
passwd=$3

PS3='\Tools\'

# bash select
select path in '/home/mel/Documents/csharp/ConsoleNotes/bin/Release'
do
ftp -in <<EOF
open $ftp_site
user $username$passwd
cd $path
put $1
close 
bye
EOF
echo$1 uploaded to $path ! 

# Break, otherwise endless loop
break
done
