#!/bin/bash
#Say is just an script  that works as a shurctut for  the speak-ng program which talks
#And on this way what it does is just read the data sved on a single file and it just say it 


mkdir ~/.logs;
touch ~/.logs/talk-voice
echo "$@" > ~/.logs/talk-voice

speak-ng -f ~/.logs/talk-voice
