#!/bin/bash

print yellow '
#slowdown
#ffmpeg -i input.mp4 -vf "setpts=2.0*PTS" output.mp4
'
print green '
#speedup
#ffmpeg -i input.mp4 -vf "setpts=0.5*PTS" output.mp4
'

ffmpeg -i $1 -vf "setpts=$2*PTS" $3

#slowdown
#ffmpeg -i input.mp4 -vf "setpts=2.0*PTS" output.mp4

#speedup
#ffmpeg -i input.mp4 -vf "setpts=0.5*PTS" output.mp4
