#!/bin/bash
sudo apt install iptables

sudo sysctl -w net.ipv4.ip_forward=1
#blootooth -> wifi
sudo iptables -A FORWARD -i bnep0 -o wlp3s0 -m state --state RELATED,ESTABLISHED -j ACCEPT

#wifi -> blootooth
sudo iptables -A FORWARD -i wlp3s0 -o bnep0 -j ACCEPT

